# SAM FILE
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A starter AWS Lambda function.
Resources:
  awscostlinepython3:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: src/
      Description: A starter AWS Lambda function.
      MemorySize: 128
      Timeout: 3
      Environment:
        Variables:
          LINE_CHANNEL_ACCESS_TOKEN: XXXXXXXXXXXXXXXXXXXX
          REGION_NAME: !Ref AWS::Region
      Events:
        awscostlineAPI:
          Type: Api
          Properties:
            Path: /cost-api
            Method: POST